package com.kopiitem.upload.ui;

import com.kopiitem.upload.common.FileProxy;
import com.kopiitem.upload.common.ModuleEnum;
import com.kopiitem.upload.common.ProjectEnum;
import com.kopiitem.upload.common.TrackEnum;
import com.kopiitem.upload.exception.CustomException;
import com.kopiitem.upload.service.UploadManager;
import com.kopiitem.upload.util.StringFormater;
import java.awt.TrayIcon;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author donny.fm
 */
public class UploadJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UploadJFrame
     */
    public UploadJFrame() {
        initComponents();
        
        initModule();
        initProject();
        initTrack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupLogMenu = new javax.swing.JPopupMenu();
        clearLogMenuItem = new javax.swing.JMenuItem();
        popupTexAreaMenu = new javax.swing.JPopupMenu();
        clearTextMenuItem = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        fromProjectCbx = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromTrackCbx = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        toProjectCbx = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        toTrackCbx = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jProgressBar = new javax.swing.JProgressBar();
        moduleCbx = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        runBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTxt = new javax.swing.JTextArea();

        clearLogMenuItem.setText("Clear");
        clearLogMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogMenuItemActionPerformed(evt);
            }
        });
        popupLogMenu.add(clearLogMenuItem);

        clearTextMenuItem.setText("Clear");
        clearTextMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextMenuItemActionPerformed(evt);
            }
        });
        popupTexAreaMenu.add(clearTextMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File Upload v1.0");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "From", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");

        jLabel3.setText("Project");

        jLabel4.setText("Track");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromTrackCbx, 0, 58, Short.MAX_VALUE)
                    .addComponent(fromProjectCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromProjectCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromTrackCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel7.setText("Project");

        jLabel8.setText("Track");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toTrackCbx, 0, 58, Short.MAX_VALUE)
                    .addComponent(toProjectCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toProjectCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toTrackCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textArea.setRows(5);
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea.setInheritsPopupMenu(true);
        textArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        jProgressBar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(0, 153, 51));
        jProgressBar.setStringPainted(true);

        jLabel9.setText("Module");

        runBtn.setText("Run");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });

        logTxt.setColumns(20);
        logTxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        logTxt.setRows(5);
        logTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        logTxt.setInheritsPopupMenu(true);
        logTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logTxtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(logTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(moduleCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moduleCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        
        if (textArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Insert Your Detail File In The Text Area Field!", "Error Message", TrayIcon.MessageType.ERROR.ordinal());
            return;
        }
        
        final UploadManager uploadManager = new UploadManager(new FileProxy(
                ProjectEnum.valueOf(fromProjectCbx.getSelectedItem().toString().toUpperCase()),
                TrackEnum.valueOf(fromTrackCbx.getSelectedItem().toString().toUpperCase()),
                ProjectEnum.valueOf(toProjectCbx.getSelectedItem().toString().toUpperCase()),
                TrackEnum.valueOf(toTrackCbx.getSelectedItem().toString().toUpperCase()),
                ModuleEnum.valueOf(moduleCbx.getSelectedItem().toString().toUpperCase())
        ));
        
        Thread t = new Thread(new Runnable() {
            
            @Override
            public void run() {
                int total = jProgressBar.getMaximum();
                String[] text = textArea.getText().split("\n");
                int line = text.length;
                
                int step = total / line;
                
                int value = 0;
                int index = 1;
                
                boolean success = true;
                while (value < total && success) {
                    try {
                        uploadManager.doUploadByFile(text[index - 1], index);
                        logTxt.append(uploadManager.getLog());
                        Thread.sleep(500l);
                        value = value + step;
                        if (index == line) {
                            value = total;
                        }
                        jProgressBar.setValue(value);
                        index++;
                        
                    } catch (InterruptedException | IOException | CustomException ex) {
                        success = false;
                        JOptionPane.showMessageDialog(null, "Something Went Error, Please check Log!", "Error Message", TrayIcon.MessageType.ERROR.ordinal());
                        Logger.getLogger(UploadJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        logTxt.append(StringFormater.handleException(ex) + "\n\n");
                    }
                    
                }
                if (success) {
                    JOptionPane.showMessageDialog(null, "All File Has been Copied!", "Information Message", TrayIcon.MessageType.WARNING.ordinal());
                    logTxt.append("All File Has been Copied!" + "\n\n");
                }
            }
        });
        t.start();

    }//GEN-LAST:event_runBtnActionPerformed

    private void logTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logTxtMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            logTxt.setComponentPopupMenu(popupLogMenu);
        }
    }//GEN-LAST:event_logTxtMouseClicked

    private void clearTextMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextMenuItemActionPerformed
        textArea.setText("");
    }//GEN-LAST:event_clearTextMenuItemActionPerformed

    private void textAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            textArea.setComponentPopupMenu(popupTexAreaMenu);
        }
    }//GEN-LAST:event_textAreaMouseClicked

    private void clearLogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogMenuItemActionPerformed
        logTxt.setText("");
    }//GEN-LAST:event_clearLogMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clearLogMenuItem;
    private javax.swing.JMenuItem clearTextMenuItem;
    private javax.swing.JComboBox fromProjectCbx;
    private javax.swing.JComboBox fromTrackCbx;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logTxt;
    private javax.swing.JComboBox moduleCbx;
    private javax.swing.JPopupMenu popupLogMenu;
    private javax.swing.JPopupMenu popupTexAreaMenu;
    private javax.swing.JButton runBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JComboBox toProjectCbx;
    private javax.swing.JComboBox toTrackCbx;
    // End of variables declaration//GEN-END:variables

    private void initModule() {
        String[] items = new String[ModuleEnum.values().length];
        int x = 0;
        for (ModuleEnum moduleEnum : ModuleEnum.values()) {
            items[x] = moduleEnum.getDesc();
            x++;
        }
        moduleCbx.setModel(new javax.swing.DefaultComboBoxModel(items));
        
    }
    
    private void initProject() {
        String[] items = new String[ProjectEnum.values().length];
        int x = 0;
        for (ProjectEnum projectEnum : ProjectEnum.values()) {
            items[x] = projectEnum.name();
            x++;
        }
        fromProjectCbx.setModel(new javax.swing.DefaultComboBoxModel(items));
        toProjectCbx.setModel(new javax.swing.DefaultComboBoxModel(items));
    }
    
    private void initTrack() {
        String[] items = new String[TrackEnum.values().length];
        int x = 0;
        for (TrackEnum trackEnum : TrackEnum.values()) {
            items[x] = trackEnum.name();
            x++;
        }
        fromTrackCbx.setModel(new javax.swing.DefaultComboBoxModel(items));
        toTrackCbx.setModel(new javax.swing.DefaultComboBoxModel(items));
    }
    
}
