package com.kopiitem.gamsuit.client.ui;

import com.kopiitem.gamsuit.client.Information;
import com.kopiitem.gamsuit.client.Player;
import com.kopiitem.gamsuit.util.BidEnum;
import com.kopiitem.gamsuit.util.CommandEnum;
import com.kopiitem.gamsuit.util.Transport;
import java.awt.TrayIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author donny.fm
 */
public class Board extends javax.swing.JFrame {

    private Player player;
    private Transport transport;

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        player = new Player();
        transport = new Transport();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stoneBtn = new javax.swing.JButton();
        scissorBtn = new javax.swing.JButton();
        paperBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        secondBetLabel = new javax.swing.JLabel();
        firstBetLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serverTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        playerNameTxt = new javax.swing.JTextField();
        portTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        firstPlayerNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        secondPlayerNameLabel = new javax.swing.JLabel();
        firstPlayerScoreLabel = new javax.swing.JLabel();
        secondPlayerScoreLabel = new javax.swing.JLabel();
        connectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        stoneBtn.setText("Stone");
        stoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoneBtnActionPerformed(evt);
            }
        });

        scissorBtn.setText("Scissor");
        scissorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorBtnActionPerformed(evt);
            }
        });

        paperBtn.setText("Paper");
        paperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Game Board"));

        secondBetLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        secondBetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondBetLabel.setText("0");

        firstBetLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        firstBetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstBetLabel.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(firstBetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(secondBetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstBetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(secondBetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Information"));

        jLabel3.setText("Server");

        serverTxt.setText("192.168.5.95");

        jLabel4.setText("Name Player");

        portTxt.setText("9090");

        jLabel5.setText("Port");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(serverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portTxt))
                    .addComponent(playerNameTxt))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(playerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Score"));
        jPanel4.setName(""); // NOI18N

        firstPlayerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstPlayerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPlayerNameLabel.setText("Player1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VS");

        secondPlayerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondPlayerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondPlayerNameLabel.setText("Player1");

        firstPlayerScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstPlayerScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPlayerScoreLabel.setText("-");
        firstPlayerScoreLabel.setToolTipText("");

        secondPlayerScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondPlayerScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondPlayerScoreLabel.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(firstPlayerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondPlayerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(firstPlayerScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(secondPlayerScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPlayerNameLabel)
                    .addComponent(jLabel2)
                    .addComponent(secondPlayerNameLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPlayerScoreLabel)
                    .addComponent(secondPlayerScoreLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        connectBtn.setText("Connect");
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(stoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scissorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(connectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scissorBtn)
                    .addComponent(paperBtn)
                    .addComponent(stoneBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        if (serverTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Type Server location!", "Error Message", TrayIcon.MessageType.ERROR.ordinal());
            return;
        }
        if (portTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Type Server location!", "Error Message", TrayIcon.MessageType.ERROR.ordinal());
            return;
        }
        if (playerNameTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Type Player Name!", "Error Message", TrayIcon.MessageType.ERROR.ordinal());
            return;
        }

        transport.create(serverTxt.getText(), Integer.parseInt(portTxt.getText()));
        player.getUser().setName(playerNameTxt.getText());
        player.setCommandEnum(CommandEnum.HANDSHAKE);
        transport.send(player);
        player = transport.read();
        if (player.getCommandEnum() == CommandEnum.CONNECTED) {
            serverTxt.setEnabled(false);
            portTxt.setEnabled(false);
            playerNameTxt.setEnabled(false);
            connectBtn.setEnabled(false);
            connectBtn.setText("Connected");

            printPlayerInformation();

            player.setCommandEnum(CommandEnum.CONNECTED);

        }

    }//GEN-LAST:event_connectBtnActionPerformed
    private void printPlayerInformation() {
        Information user = player.getUser();
        Information robot = player.getRobot();

        firstPlayerNameLabel.setText(user.getName());
        secondPlayerNameLabel.setText(robot.getName());

        firstPlayerScoreLabel.setText(String.valueOf(user.getScore()));
        secondPlayerScoreLabel.setText(String.valueOf(robot.getScore()));

        firstBetLabel.setText("");
        secondBetLabel.setText("");
        if (user.getBid() != null) {
            firstBetLabel.setText(user.getBid().name());
        }
        if (robot.getBid() != null) {
            secondBetLabel.setText(robot.getBid().name());
        }

    }

    private void send(CommandEnum commandEnum) {
        player.setCommandEnum(commandEnum);
        transport.send(player);
        player = transport.read();
        printPlayerInformation();
    }

    private void stoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoneBtnActionPerformed
        player.getUser().setBid(BidEnum.STONE);
        send(CommandEnum.PLAY);
    }//GEN-LAST:event_stoneBtnActionPerformed

    private void paperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperBtnActionPerformed
        player.getUser().setBid(BidEnum.PAPER);
        send(CommandEnum.PLAY);
    }//GEN-LAST:event_paperBtnActionPerformed

    private void scissorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorBtnActionPerformed
        player.getUser().setBid(BidEnum.SCISSOR);
        send(CommandEnum.PLAY);
    }//GEN-LAST:event_scissorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectBtn;
    private javax.swing.JLabel firstBetLabel;
    private javax.swing.JLabel firstPlayerNameLabel;
    private javax.swing.JLabel firstPlayerScoreLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton paperBtn;
    private javax.swing.JTextField playerNameTxt;
    private javax.swing.JTextField portTxt;
    private javax.swing.JButton scissorBtn;
    private javax.swing.JLabel secondBetLabel;
    private javax.swing.JLabel secondPlayerNameLabel;
    private javax.swing.JLabel secondPlayerScoreLabel;
    private javax.swing.JTextField serverTxt;
    private javax.swing.JButton stoneBtn;
    // End of variables declaration//GEN-END:variables
}
